package com.assertion;

import com.driver.DriverManager;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.List;

public class AssertionWait extends WebDriverWait {

    private static final List<Class<? extends Throwable>> COMMON_RETRY_EXCEPTIONS =
            List.of(StaleElementReferenceException.class);


    private final String timeoutMessage;

    /**
     * Creates an AssertionWait with the specified timeout.
     *
     * @param timeout assertion timeout
     */
    public AssertionWait(Duration timeout) {
        this(timeout, "Assertion condition was not satisfied.");
    }

    /**
     * Creates an AssertionWait with the specified timeout and message.
     *
     * @param timeout        assertion timeout
     * @param timeoutMessage message to use when the assertion times out
     */
    public AssertionWait(Duration timeout, String timeoutMessage) {
        super(DriverManager.getDriver(), timeout, DriverManager.getPollingInterval());
        this.timeoutMessage = timeoutMessage;
        ignoreAll(COMMON_RETRY_EXCEPTIONS);
    }

    /**
     * Creates the exception thrown when the assertion times out.
     *
     * @param message       timeout message generated by WebDriverWait
     * @param lastException last exception encountered during polling
     * @return assertion timeout exception
     */
    @Override
    protected RuntimeException timeoutException(String message, Throwable lastException) {
        return new AssertionTimeoutException(timeoutMessage, lastException);
    }
}
